use super::{Language, DATA_DIR};

use std::fmt;
use std::path::PathBuf;

const QUOTES_DIR: &str = "quotes";

pub enum QuoteLanguage {
    Afrikaans,
    Albanian,
    Arabic,
    ArabicEgypt,
    Bangla,
    Belarusian,
    BelarusianLacinka,
    Bulgarian,
    ChineseSimplified,
    CodeArduino,
    CodeAssembly,
    CodeC,
    CodeCSS,
    CodeCSharp,
    CodeCpp,
    CodeCuda,
    CodeGo,
    CodeJava,
    CodeJavascript,
    CodeJule,
    CodeJulia,
    CodeKotlin,
    CodeLua,
    CodeNim,
    CodePhp,
    CodePython,
    CodeR,
    CodeRuby,
    CodeRust,
    CodeSystemVerilog,
    CodeTypescript,
    CodeYoptascript,
    Czech,
    Danish,
    DockerFile,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Filipino,
    Finnish,
    French,
    Georgian,
    German,
    Hebrew,
    Hindi,
    Icelandic,
    Indonesian,
    Irish,
    Italian,
    Kannada,
    Kazakh,
    Korean,
    Latin,
    Lithuanian,
    Malagasy,
    Malayalam,
    Marathi,
    Mongolian,
    Nepali,
    NorwegianBokmal,
    NorwegianNynorsk,
    Persian,
    Polish,
    Portuguese,
    Romanian,
    Russian,
    Sanskrit,
    Serbian,
    Slovak,
    Spanish,
    Swedish,
    Tamil,
    Thai,
    TokiPona,
    Turkish,
    Ukrainian,
    Urdu,
    Vietnamese,
}

impl QuoteLanguage {
    pub fn dir() -> PathBuf {
        PathBuf::from(DATA_DIR).join(QUOTES_DIR)
    }

    pub fn from_language(language: Language) -> crate::Result<QuoteLanguage> {
        match language {
            Language::Afrikaans10k => Ok(QuoteLanguage::Afrikaans),
            Language::Afrikaans => Ok(QuoteLanguage::Afrikaans),
            Language::Afrikaans1k => Ok(QuoteLanguage::Afrikaans),
            Language::Albanian => Ok(QuoteLanguage::Albanian),
            Language::Albanian1k => Ok(QuoteLanguage::Albanian),
            Language::Arabic => Ok(QuoteLanguage::Arabic),
            Language::Arabic10k => Ok(QuoteLanguage::Arabic),
            Language::ArabicEgypt => Ok(QuoteLanguage::ArabicEgypt),
            Language::ArabicEgypt1k => Ok(QuoteLanguage::ArabicEgypt),
            Language::Bangla => Ok(QuoteLanguage::Bangla),
            Language::Bangla10k => Ok(QuoteLanguage::Bangla),
            Language::BanglaLetters => Ok(QuoteLanguage::Bangla),
            Language::Belarusian => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian100k => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian10k => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian1k => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian25k => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian50k => Ok(QuoteLanguage::Belarusian),
            Language::Belarusian5k => Ok(QuoteLanguage::Belarusian),
            Language::BelarusianLacinka => Ok(QuoteLanguage::BelarusianLacinka),
            Language::BelarusianLacinka1k => Ok(QuoteLanguage::BelarusianLacinka),
            Language::Bulgarian => Ok(QuoteLanguage::Bulgarian),
            Language::BulgarianLatin => Ok(QuoteLanguage::Bulgarian),
            Language::ChineseSimplified => Ok(QuoteLanguage::ChineseSimplified),
            Language::ChineseSimplified10k => Ok(QuoteLanguage::ChineseSimplified),
            Language::ChineseSimplified1k => Ok(QuoteLanguage::ChineseSimplified),
            Language::ChineseSimplified50k => Ok(QuoteLanguage::ChineseSimplified),
            Language::ChineseSimplified5k => Ok(QuoteLanguage::ChineseSimplified),
            Language::CodeArduino => Ok(QuoteLanguage::CodeArduino),
            Language::CodeAssembly => Ok(QuoteLanguage::CodeAssembly),
            Language::CodeC => Ok(QuoteLanguage::CodeC),
            Language::CodeCpp => Ok(QuoteLanguage::CodeCpp),
            Language::CodeCSS => Ok(QuoteLanguage::CodeCSS),
            Language::CodeCSharp => Ok(QuoteLanguage::CodeCSharp),
            Language::CodeCuda => Ok(QuoteLanguage::CodeCuda),
            Language::CodeGo => Ok(QuoteLanguage::CodeGo),
            Language::CodeJava => Ok(QuoteLanguage::CodeJava),
            Language::CodeJavascript => Ok(QuoteLanguage::CodeJavascript),
            Language::CodeJavascript1k => Ok(QuoteLanguage::CodeJavascript),
            Language::CodeJavascriptReact => Ok(QuoteLanguage::CodeJavascript),
            Language::CodeJule => Ok(QuoteLanguage::CodeJule),
            Language::CodeJulia => Ok(QuoteLanguage::CodeJulia),
            Language::CodeKotlin => Ok(QuoteLanguage::CodeKotlin),
            Language::CodeLua => Ok(QuoteLanguage::CodeLua),
            Language::CodeNim => Ok(QuoteLanguage::CodeNim),
            Language::CodePhp => Ok(QuoteLanguage::CodePhp),
            Language::CodePython => Ok(QuoteLanguage::CodePython),
            Language::CodePython1k => Ok(QuoteLanguage::CodePython),
            Language::CodePython2k => Ok(QuoteLanguage::CodePython),
            Language::CodePython5k => Ok(QuoteLanguage::CodePython),
            Language::CodeR => Ok(QuoteLanguage::CodeR),
            Language::CodeR2k => Ok(QuoteLanguage::CodeR),
            Language::CodeRuby => Ok(QuoteLanguage::CodeRuby),
            Language::CodeRust => Ok(QuoteLanguage::CodeRust),
            Language::CodeSystemVerilog => Ok(QuoteLanguage::CodeSystemVerilog),
            Language::CodeTypescript => Ok(QuoteLanguage::CodeTypescript),
            Language::CodeYoptascript => Ok(QuoteLanguage::CodeYoptascript),
            Language::Czech => Ok(QuoteLanguage::Czech),
            Language::Czech10k => Ok(QuoteLanguage::Czech),
            Language::Czech1k => Ok(QuoteLanguage::Czech),
            Language::Danish => Ok(QuoteLanguage::Danish),
            Language::Danish10k => Ok(QuoteLanguage::Danish),
            Language::Danish1k => Ok(QuoteLanguage::Danish),
            Language::DockerFile => Ok(QuoteLanguage::DockerFile),
            Language::Dutch => Ok(QuoteLanguage::Dutch),
            Language::Dutch10k => Ok(QuoteLanguage::Dutch),
            Language::Dutch1k => Ok(QuoteLanguage::Dutch),
            Language::English => Ok(QuoteLanguage::English),
            Language::English10k => Ok(QuoteLanguage::English),
            Language::English1k => Ok(QuoteLanguage::English),
            Language::English25k => Ok(QuoteLanguage::English),
            Language::English450k => Ok(QuoteLanguage::English),
            Language::English5k => Ok(QuoteLanguage::English),
            Language::EnglishCommonlyMisspelled => Ok(QuoteLanguage::English),
            Language::EnglishContractions => Ok(QuoteLanguage::English),
            Language::EnglishDoubleletter => Ok(QuoteLanguage::English),
            Language::EnglishMedical => Ok(QuoteLanguage::English),
            Language::EnglishOld => Ok(QuoteLanguage::English),
            Language::EnglishShakespearean => Ok(QuoteLanguage::English),
            Language::Esperanto => Ok(QuoteLanguage::Esperanto),
            Language::Esperanto10k => Ok(QuoteLanguage::Esperanto),
            Language::Esperanto1k => Ok(QuoteLanguage::Esperanto),
            Language::Esperanto25k => Ok(QuoteLanguage::Esperanto),
            Language::Esperanto36k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoHSistemo => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoHSistemo10k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoHSistemo1k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoHSistemo25k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoHSistemo36k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoXSistemo => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoXSistemo10k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoXSistemo1k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoXSistemo25k => Ok(QuoteLanguage::Esperanto),
            Language::EsperantoXSistemo36k => Ok(QuoteLanguage::Esperanto),
            Language::Estonian => Ok(QuoteLanguage::Estonian),
            Language::Estonian10k => Ok(QuoteLanguage::Estonian),
            Language::Estonian1k => Ok(QuoteLanguage::Estonian),
            Language::Estonian5k => Ok(QuoteLanguage::Estonian),
            Language::Filipino => Ok(QuoteLanguage::Filipino),
            Language::Filipino1k => Ok(QuoteLanguage::Filipino),
            Language::Finnish => Ok(QuoteLanguage::Finnish),
            Language::Finnish10k => Ok(QuoteLanguage::Finnish),
            Language::Finnish1k => Ok(QuoteLanguage::Finnish),
            Language::French => Ok(QuoteLanguage::French),
            Language::French10k => Ok(QuoteLanguage::French),
            Language::French1k => Ok(QuoteLanguage::French),
            Language::French2k => Ok(QuoteLanguage::French),
            Language::French600k => Ok(QuoteLanguage::French),
            Language::FrenchBitoduc => Ok(QuoteLanguage::French),
            Language::Georgian => Ok(QuoteLanguage::Georgian),
            Language::German => Ok(QuoteLanguage::German),
            Language::German10k => Ok(QuoteLanguage::German),
            Language::German1k => Ok(QuoteLanguage::German),
            Language::German250k => Ok(QuoteLanguage::German),
            Language::Hebrew => Ok(QuoteLanguage::Hebrew),
            Language::Hebrew10k => Ok(QuoteLanguage::Hebrew),
            Language::Hebrew1k => Ok(QuoteLanguage::Hebrew),
            Language::Hebrew5k => Ok(QuoteLanguage::Hebrew),
            Language::Hindi => Ok(QuoteLanguage::Hindi),
            Language::Hindi1k => Ok(QuoteLanguage::Hindi),
            Language::Icelandic => Ok(QuoteLanguage::Icelandic),
            Language::Icelandic1k => Ok(QuoteLanguage::Icelandic),
            Language::Indonesian => Ok(QuoteLanguage::Indonesian),
            Language::Indonesian10k => Ok(QuoteLanguage::Indonesian),
            Language::Indonesian1k => Ok(QuoteLanguage::Indonesian),
            Language::Irish => Ok(QuoteLanguage::Irish),
            Language::Italian => Ok(QuoteLanguage::Italian),
            Language::Italian1k => Ok(QuoteLanguage::Italian),
            Language::Italian280k => Ok(QuoteLanguage::Italian),
            Language::Italian60k => Ok(QuoteLanguage::Italian),
            Language::Italian7k => Ok(QuoteLanguage::Italian),
            Language::Kannada => Ok(QuoteLanguage::Kannada),
            Language::Kazakh => Ok(QuoteLanguage::Kazakh),
            Language::Kazakh1k => Ok(QuoteLanguage::Kazakh),
            Language::Korean => Ok(QuoteLanguage::Korean),
            Language::Korean1k => Ok(QuoteLanguage::Korean),
            Language::Korean5k => Ok(QuoteLanguage::Korean),
            Language::Latin => Ok(QuoteLanguage::Latin),
            Language::Lithuanian => Ok(QuoteLanguage::Lithuanian),
            Language::Lithuanian1k => Ok(QuoteLanguage::Lithuanian),
            Language::Lithuanian3k => Ok(QuoteLanguage::Lithuanian),
            Language::Malagasy => Ok(QuoteLanguage::Malagasy),
            Language::Malagasy1k => Ok(QuoteLanguage::Malagasy),
            Language::Malayalam => Ok(QuoteLanguage::Malayalam),
            Language::Marathi => Ok(QuoteLanguage::Marathi),
            Language::Mongolian => Ok(QuoteLanguage::Mongolian),
            Language::Mongolian10k => Ok(QuoteLanguage::Mongolian),
            Language::Nepali => Ok(QuoteLanguage::Nepali),
            Language::Nepali1k => Ok(QuoteLanguage::Nepali),
            Language::NepaliRomanized => Ok(QuoteLanguage::Nepali),
            Language::NorwegianBokmal => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianBokmal10k => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianBokmal150k => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianBokmal1k => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianBokmal5k => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianBokmal600k => Ok(QuoteLanguage::NorwegianBokmal),
            Language::NorwegianNynorsk => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::NorwegianNynorsk100k => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::NorwegianNynorsk10k => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::NorwegianNynorsk1k => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::NorwegianNynorsk400k => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::NorwegianNynorsk5k => Ok(QuoteLanguage::NorwegianNynorsk),
            Language::Persian => Ok(QuoteLanguage::Persian),
            Language::Persian1k => Ok(QuoteLanguage::Persian),
            Language::Persian20k => Ok(QuoteLanguage::Persian),
            Language::Persian5k => Ok(QuoteLanguage::Persian),
            Language::PersianRomanized => Ok(QuoteLanguage::Persian),
            Language::Polish => Ok(QuoteLanguage::Polish),
            Language::Polish10k => Ok(QuoteLanguage::Polish),
            Language::Polish200k => Ok(QuoteLanguage::Polish),
            Language::Polish20k => Ok(QuoteLanguage::Polish),
            Language::Polish2k => Ok(QuoteLanguage::Polish),
            Language::Polish40k => Ok(QuoteLanguage::Polish),
            Language::Polish5k => Ok(QuoteLanguage::Polish),
            Language::Portuguese => Ok(QuoteLanguage::Portuguese),
            Language::Portuguese1k => Ok(QuoteLanguage::Portuguese),
            Language::Portuguese320k => Ok(QuoteLanguage::Portuguese),
            Language::Portuguese3k => Ok(QuoteLanguage::Portuguese),
            Language::Portuguese550k => Ok(QuoteLanguage::Portuguese),
            Language::Portuguese5k => Ok(QuoteLanguage::Portuguese),
            Language::PortugueseAcentosECedilha => Ok(QuoteLanguage::Portuguese),
            Language::Romanian => Ok(QuoteLanguage::Romanian),
            Language::Romanian100k => Ok(QuoteLanguage::Romanian),
            Language::Romanian10k => Ok(QuoteLanguage::Romanian),
            Language::Romanian1k => Ok(QuoteLanguage::Romanian),
            Language::Romanian200k => Ok(QuoteLanguage::Romanian),
            Language::Romanian25k => Ok(QuoteLanguage::Romanian),
            Language::Romanian50k => Ok(QuoteLanguage::Romanian),
            Language::Romanian5k => Ok(QuoteLanguage::Romanian),
            Language::Russian => Ok(QuoteLanguage::Russian),
            Language::Russian10k => Ok(QuoteLanguage::Russian),
            Language::Russian1k => Ok(QuoteLanguage::Russian),
            Language::Russian25k => Ok(QuoteLanguage::Russian),
            Language::Russian375k => Ok(QuoteLanguage::Russian),
            Language::Russian50k => Ok(QuoteLanguage::Russian),
            Language::Russian5k => Ok(QuoteLanguage::Russian),
            Language::RussianAbbreviations => Ok(QuoteLanguage::Russian),
            Language::RussianContractions => Ok(QuoteLanguage::Russian),
            Language::RussianContractions1k => Ok(QuoteLanguage::Russian),
            Language::Sanskrit => Ok(QuoteLanguage::Sanskrit),
            Language::SanskritRoman => Ok(QuoteLanguage::Sanskrit),
            Language::Serbian => Ok(QuoteLanguage::Serbian),
            Language::Serbian10k => Ok(QuoteLanguage::Serbian),
            Language::Slovak => Ok(QuoteLanguage::Slovak),
            Language::Slovak10k => Ok(QuoteLanguage::Slovak),
            Language::Slovak1k => Ok(QuoteLanguage::Slovak),
            Language::Spanish => Ok(QuoteLanguage::Spanish),
            Language::Spanish10k => Ok(QuoteLanguage::Spanish),
            Language::Spanish1k => Ok(QuoteLanguage::Spanish),
            Language::Spanish650k => Ok(QuoteLanguage::Spanish),
            Language::Swedish => Ok(QuoteLanguage::Swedish),
            Language::Swedish1k => Ok(QuoteLanguage::Swedish),
            Language::SwedishDiacritics => Ok(QuoteLanguage::Swedish),
            Language::Tamil => Ok(QuoteLanguage::Tamil),
            Language::Tamil1k => Ok(QuoteLanguage::Tamil),
            Language::TamilOld => Ok(QuoteLanguage::Tamil),
            Language::Thai => Ok(QuoteLanguage::Thai),
            Language::Thai10k => Ok(QuoteLanguage::Thai),
            Language::Thai1k => Ok(QuoteLanguage::Thai),
            Language::Thai20k => Ok(QuoteLanguage::Thai),
            Language::Thai50k => Ok(QuoteLanguage::Thai),
            Language::Thai5k => Ok(QuoteLanguage::Thai),
            Language::Thai60k => Ok(QuoteLanguage::Thai),
            Language::TokiPona => Ok(QuoteLanguage::TokiPona),
            Language::TokiPonaKuLili => Ok(QuoteLanguage::TokiPona),
            Language::TokiPonaKuSuli => Ok(QuoteLanguage::TokiPona),
            Language::Turkish => Ok(QuoteLanguage::Turkish),
            Language::Turkish1k => Ok(QuoteLanguage::Turkish),
            Language::Turkish5k => Ok(QuoteLanguage::Turkish),
            Language::Ukrainian => Ok(QuoteLanguage::Ukrainian),
            Language::Ukrainian10k => Ok(QuoteLanguage::Ukrainian),
            Language::Ukrainian1k => Ok(QuoteLanguage::Ukrainian),
            Language::Ukrainian50k => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianEndings => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianLatynka => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianLatynka10k => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianLatynka1k => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianLatynka50k => Ok(QuoteLanguage::Ukrainian),
            Language::UkrainianLatynkaEndings => Ok(QuoteLanguage::Ukrainian),
            Language::Urdu => Ok(QuoteLanguage::Urdu),
            Language::Urdu1k => Ok(QuoteLanguage::Urdu),
            Language::Urdu5k => Ok(QuoteLanguage::Urdu),
            Language::Vietnamese => Ok(QuoteLanguage::Vietnamese),
            Language::Vietnamese1k => Ok(QuoteLanguage::Vietnamese),
            Language::Vietnamese5k => Ok(QuoteLanguage::Vietnamese),
            _ => Err("Language {language} doesn't have any quotes.".into()),
        }
    }
}

impl fmt::Display for QuoteLanguage {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let string = match self {
            QuoteLanguage::Afrikaans => "afrikaans",
            QuoteLanguage::Albanian => "albanian",
            QuoteLanguage::Arabic => "arabic",
            QuoteLanguage::ArabicEgypt => "arabic_egypt",
            QuoteLanguage::Bangla => "bangla",
            QuoteLanguage::Belarusian => "belarusian",
            QuoteLanguage::BelarusianLacinka => "belarusian_lacinka",
            QuoteLanguage::Bulgarian => "bulgarian",
            QuoteLanguage::ChineseSimplified => "chinese_simplified",
            QuoteLanguage::CodeArduino => "code_arduino",
            QuoteLanguage::CodeAssembly => "code_assembly",
            QuoteLanguage::CodeCpp => "code_c++",
            QuoteLanguage::CodeC => "code_c",
            QuoteLanguage::CodeCSharp => "code_csharp",
            QuoteLanguage::CodeCSS => "code_css",
            QuoteLanguage::CodeCuda => "code_cuda",
            QuoteLanguage::CodeGo => "code_go",
            QuoteLanguage::CodeJava => "code_java",
            QuoteLanguage::CodeJavascript => "code_javascript",
            QuoteLanguage::CodeJule => "code_jule",
            QuoteLanguage::CodeJulia => "code_julia",
            QuoteLanguage::CodeKotlin => "code_kotlin",
            QuoteLanguage::CodeLua => "code_lua",
            QuoteLanguage::CodeNim => "code_nim",
            QuoteLanguage::CodePhp => "code_php",
            QuoteLanguage::CodePython => "code_python",
            QuoteLanguage::CodeR => "code_r",
            QuoteLanguage::CodeRuby => "code_ruby",
            QuoteLanguage::CodeRust => "code_rust",
            QuoteLanguage::CodeSystemVerilog => "code_systemverilog",
            QuoteLanguage::CodeTypescript => "code_typescript",
            QuoteLanguage::CodeYoptascript => "code_yoptascript",
            QuoteLanguage::Czech => "czech",
            QuoteLanguage::Danish => "danish",
            QuoteLanguage::DockerFile => "docker_file",
            QuoteLanguage::Dutch => "dutch",
            QuoteLanguage::English => "english",
            QuoteLanguage::Esperanto => "esperanto",
            QuoteLanguage::Estonian => "estonian",
            QuoteLanguage::Filipino => "filipino",
            QuoteLanguage::Finnish => "finnish",
            QuoteLanguage::French => "french",
            QuoteLanguage::Georgian => "georgian",
            QuoteLanguage::German => "german",
            QuoteLanguage::Hebrew => "hebrew",
            QuoteLanguage::Hindi => "hindi",
            QuoteLanguage::Icelandic => "icelandic",
            QuoteLanguage::Indonesian => "indonesian",
            QuoteLanguage::Irish => "irish",
            QuoteLanguage::Italian => "italian",
            QuoteLanguage::Kannada => "kannada",
            QuoteLanguage::Kazakh => "kazakh",
            QuoteLanguage::Korean => "korean",
            QuoteLanguage::Latin => "latin",
            QuoteLanguage::Lithuanian => "lithuanian",
            QuoteLanguage::Malagasy => "malagasy",
            QuoteLanguage::Malayalam => "malayalam",
            QuoteLanguage::Marathi => "marathi",
            QuoteLanguage::Mongolian => "mongolian",
            QuoteLanguage::Nepali => "nepali",
            QuoteLanguage::NorwegianBokmal => "norwegian_bokmal",
            QuoteLanguage::NorwegianNynorsk => "norwegian_nynorsk",
            QuoteLanguage::Persian => "persian",
            QuoteLanguage::Polish => "polish",
            QuoteLanguage::Portuguese => "portuguese",
            QuoteLanguage::Romanian => "romanian",
            QuoteLanguage::Russian => "russian",
            QuoteLanguage::Sanskrit => "sanskrit",
            QuoteLanguage::Serbian => "serbian",
            QuoteLanguage::Slovak => "slovak",
            QuoteLanguage::Spanish => "spanish",
            QuoteLanguage::Swedish => "swedish",
            QuoteLanguage::Tamil => "tamil",
            QuoteLanguage::Thai => "thai",
            QuoteLanguage::TokiPona => "toki_pona",
            QuoteLanguage::Turkish => "turkish",
            QuoteLanguage::Ukrainian => "ukrainian",
            QuoteLanguage::Urdu => "urdu",
            QuoteLanguage::Vietnamese => "vietnamese",
        };

        write!(f, "{string}")
    }
}
