use crate::DATA_DIR;
use crate::typing::WordCount;

use rand::Rng;
use serde::{Deserialize, Serialize};

use std::fmt;
use std::fs;
use std::path::PathBuf;

const LANGUAGES_DIR: &str = "languages";

#[derive(Deserialize, Serialize)]
pub struct Words {
    bcp47: Option<String>,
    #[serde(default = "false_bool")]
    order_by_frequency: bool,
    #[serde(default = "false_bool")]
    right_to_left: bool,
    #[serde(default = "false_bool")]
    ligatures: bool,
    #[serde(default = "false_bool")]
    no_lazy_mode: bool,
    #[serde(default = "Vec::new")]
    additional_accents: Vec<[String; 2]>,
    words: Vec<String>,
}

fn false_bool() -> bool {
    false
}

impl Words {
    pub fn from_language(language: &Language) -> crate::Result<Self> {
        Self::from_file(language.file())
    }

    fn from_file(file: PathBuf) -> crate::Result<Self> {
        let contents = fs::read(file)?;
        let json: Self = serde_json::from_slice(&contents)?;
        Ok(json)
    }

    pub fn random(&self, count: &WordCount, punctuation: bool, numbers: bool) -> Option<Vec<&String>> {
        let mut rng = rand::rng();
        let words_len = self.words.len();

        if words_len == 0 {
            return None;
        }

        Some(
            (0..count.as_usize())
                .map(|_| self.words.get(rng.random_range(0..words_len)).unwrap())
                .collect(),
        )
    }
}

#[derive(Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum Language {
    Afrikaans10k,
    Afrikaans1k,
    Afrikaans,
    Albanian1k,
    Albanian,
    Amharic1k,
    Amharic5k,
    Amharic,
    Arabic10k,
    ArabicEgypt1k,
    ArabicEgypt,
    ArabicMorocco,
    Arabic,
    Armenian1k,
    ArmenianWestern1k,
    ArmenianWestern,
    Armenian,
    Azerbaijani1k,
    Azerbaijani,
    Bangla10k,
    BanglaLetters,
    Bangla,
    Bashkir,
    Belarusian100k,
    Belarusian10k,
    Belarusian1k,
    Belarusian25k,
    Belarusian50k,
    Belarusian5k,
    BelarusianLacinka1k,
    BelarusianLacinka,
    Belarusian,
    Bosnian4k,
    Bosnian,
    BulgarianLatin,
    Bulgarian,
    Catalan1k,
    Catalan,
    ChineseSimplified10k,
    ChineseSimplified1k,
    ChineseSimplified50k,
    ChineseSimplified5k,
    ChineseSimplified,
    ChineseTraditional,
    CodeAbap1k,
    CodeAbap,
    CodeArduino,
    CodeAssembly,
    CodeBash,
    CodeBrainfck,
    CodeC,
    CodeCpp,
    CodeCobol,
    CodeCommonLisp,
    CodeCSharp,
    CodeCSS,
    CodeCuda,
    CodeDart,
    CodeElixir,
    CodeFortran,
    CodeFSharp,
    CodeGdscript2,
    CodeGdscript,
    CodeGleam,
    CodeGo,
    CodeHaskell,
    CodeHtml,
    CodeJava,
    CodeJavascript1k,
    CodeJavascriptReact,
    CodeJavascript,
    CodeJule,
    CodeJulia,
    CodeKotlin,
    CodeLatex,
    CodeLua,
    CodeLuau,
    CodeMatlab,
    CodeNim,
    CodeNix,
    CodeOdin,
    CodeOok,
    CodeOpenCL,
    CodePascal,
    CodePerl,
    CodePhp,
    CodePowershell,
    CodePython1k,
    CodePython2k,
    CodePython5k,
    CodePython,
    CodeR2k,
    CodeR,
    CodeRockstar,
    CodeRuby,
    CodeRust,
    CodeScala,
    CodeSQL,
    CodeSwift,
    CodeSystemVerilog,
    CodeTypescript,
    CodeTypst,
    CodeV,
    CodeVim,
    CodeVimscript,
    CodeVisualBasic,
    CodeYoptascript,
    CodeZig,
    Croatian1k,
    Croatian,
    Czech10k,
    Czech1k,
    Czech,
    Danish10k,
    Danish1k,
    Danish,
    DockerFile,
    Dutch10k,
    Dutch1k,
    Dutch,
    English10k,
    English1k,
    English25k,
    English450k,
    English5k,
    EnglishCommonlyMisspelled,
    EnglishContractions,
    EnglishDoubleletter,
    EnglishMedical,
    EnglishOld,
    EnglishShakespearean,
    English,
    Esperanto10k,
    Esperanto1k,
    Esperanto25k,
    Esperanto36k,
    EsperantoHSistemo10k,
    EsperantoHSistemo1k,
    EsperantoHSistemo25k,
    EsperantoHSistemo36k,
    EsperantoHSistemo,
    EsperantoXSistemo10k,
    EsperantoXSistemo1k,
    EsperantoXSistemo25k,
    EsperantoXSistemo36k,
    EsperantoXSistemo,
    Esperanto,
    Estonian10k,
    Estonian1k,
    Estonian5k,
    Estonian,
    Euskera,
    Filipino1k,
    Filipino,
    Finnish10k,
    Finnish1k,
    Finnish,
    French10k,
    French1k,
    French2k,
    French600k,
    FrenchBitoduc,
    French,
    Frisian1k,
    Frisian,
    Friulian,
    Galician,
    Georgian,
    German10k,
    German1k,
    German250k,
    German,
    Git,
    Greek10k,
    Greek1k,
    Greek25k,
    Greek5k,
    Greek,
    Greeklish10k,
    Greeklish1k,
    Greeklish25k,
    Greeklish5k,
    Greeklish,
    Gujarati1k,
    Gujarati,
    Hausa1k,
    Hausa,
    Hawaiian1k,
    Hawaiian,
    Hebrew10k,
    Hebrew1k,
    Hebrew5k,
    Hebrew,
    Hindi1k,
    Hindi,
    Hinglish,
    Hungarian2k,
    Hungarian,
    Icelandic1k,
    Icelandic,
    Indonesian10k,
    Indonesian1k,
    Indonesian,
    Irish,
    Italian1k,
    Italian280k,
    Italian60k,
    Italian7k,
    Italian,
    JapaneseHiragana,
    JapaneseKatakana,
    JapaneseRomaji1k,
    JapaneseRomaji,
    Jyutping,
    Kabyle10k,
    Kabyle1k,
    Kabyle2k,
    Kabyle5k,
    Kabyle,
    Kannada,
    Kazakh1k,
    Kazakh,
    Khmer,
    Klingon1k,
    Klingon,
    Korean1k,
    Korean5k,
    Korean,
    KurdishCentral2k,
    KurdishCentral4k,
    KurdishCentral,
    Kyrgyz1k,
    Kyrgyz,
    Latin,
    Latvian1k,
    Latvian,
    LeagueOfLegends,
    Lithuanian1k,
    Lithuanian3k,
    Lithuanian,
    LojbanCmavo,
    LojbanGismu,
    LoremIpsum,
    Macedonian10k,
    Macedonian1k,
    Macedonian75k,
    Macedonian,
    Malagasy1k,
    Malagasy,
    Malay1k,
    Malay,
    Malayalam,
    Maltese1k,
    Maltese,
    Maori1k,
    Marathi,
    Mongolian10k,
    Mongolian,
    MyanmarBurmese,
    Nepali1k,
    NepaliRomanized,
    Nepali,
    NorwegianBokmal10k,
    NorwegianBokmal150k,
    NorwegianBokmal1k,
    NorwegianBokmal5k,
    NorwegianBokmal600k,
    NorwegianBokmal,
    NorwegianNynorsk100k,
    NorwegianNynorsk10k,
    NorwegianNynorsk1k,
    NorwegianNynorsk400k,
    NorwegianNynorsk5k,
    NorwegianNynorsk,
    Occitan10k,
    Occitan1k,
    Occitan2k,
    Occitan5k,
    Occitan,
    Oromo1k,
    Oromo5k,
    Oromo,
    Pashto,
    Persian1k,
    Persian20k,
    Persian5k,
    PersianRomanized,
    Persian,
    PigLatin,
    Pinyin10k,
    Pinyin1k,
    Pinyin,
    Polish10k,
    Polish200k,
    Polish20k,
    Polish2k,
    Polish40k,
    Polish5k,
    Polish,
    Portuguese1k,
    Portuguese320k,
    Portuguese3k,
    Portuguese550k,
    Portuguese5k,
    PortugueseAcentosECedilha,
    Portuguese,
    Quenya,
    Romanian100k,
    Romanian10k,
    Romanian1k,
    Romanian200k,
    Romanian25k,
    Romanian50k,
    Romanian5k,
    Romanian,
    Russian10k,
    Russian1k,
    Russian25k,
    Russian375k,
    Russian50k,
    Russian5k,
    RussianAbbreviations,
    RussianContractions1k,
    RussianContractions,
    Russian,
    SanskritRoman,
    Sanskrit,
    Santali,
    Serbian10k,
    SerbianLatin10k,
    SerbianLatin,
    Serbian,
    Shona1k,
    Shona,
    Sinhala,
    Slovak10k,
    Slovak1k,
    Slovak,
    Slovenian1k,
    Slovenian5k,
    Slovenian,
    Spanish10k,
    Spanish1k,
    Spanish650k,
    Spanish,
    Swahili1k,
    Swedish1k,
    SwedishDiacritics,
    Swedish,
    SwissGerman1k,
    SwissGerman2k,
    SwissGerman,
    Tamil1k,
    TamilOld,
    Tamil,
    Tanglish,
    Tatar1k,
    Tatar5k,
    Tatar9k,
    TatarCrimean10k,
    TatarCrimean15k,
    TatarCrimean1k,
    TatarCrimean5k,
    TatarCrimeanCyrillic10k,
    TatarCrimeanCyrillic15k,
    TatarCrimeanCyrillic1k,
    TatarCrimeanCyrillic5k,
    TatarCrimeanCyrillic,
    TatarCrimean,
    Tatar,
    Telugu1k,
    Telugu,
    Thai10k,
    Thai1k,
    Thai20k,
    Thai50k,
    Thai5k,
    Thai60k,
    Thai,
    Tibetan1k,
    Tibetan,
    TokiPonaKuLili,
    TokiPonaKuSuli,
    TokiPona,
    Turkish1k,
    Turkish5k,
    Turkish,
    TwitchEmotes,
    TypingOfTheDead,
    Udmurt,
    Ukrainian10k,
    Ukrainian1k,
    Ukrainian50k,
    UkrainianEndings,
    UkrainianLatynka10k,
    UkrainianLatynka1k,
    UkrainianLatynka50k,
    UkrainianLatynkaEndings,
    UkrainianLatynka,
    Ukrainian,
    Urdish,
    Urdu1k,
    Urdu5k,
    Urdu,
    Uzbek1k,
    Uzbek70k,
    Uzbek,
    Vietnamese1k,
    Vietnamese5k,
    Vietnamese,
    ViossaNjutro,
    Viossa,
    Welsh1k,
    Welsh,
    Wordle1k,
    Wordle,
    Xhosa3k,
    Xhosa,
    Yiddish,
    Yoruba1k,
    Zulu,
}

impl Language {
    pub fn dir() -> PathBuf {
        PathBuf::from(DATA_DIR).join(LANGUAGES_DIR)
    }

    pub fn file(&self) -> PathBuf {
        Self::dir().join(format!("{self}.json"))
    }
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let string = match self {
            Language::Afrikaans10k => "afrikaans_10k",
            Language::Afrikaans1k => "afrikaans_1k",
            Language::Afrikaans => "afrikaans",
            Language::Albanian1k => "albanian_1k",
            Language::Albanian => "albanian",
            Language::Amharic1k => "amharic_1k",
            Language::Amharic5k => "amharic_5k",
            Language::Amharic => "amharic",
            Language::Arabic10k => "arabic_10k",
            Language::ArabicEgypt1k => "arabic_egypt_1k",
            Language::ArabicEgypt => "arabic_egypt",
            Language::ArabicMorocco => "arabic_morocco",
            Language::Arabic => "arabic",
            Language::Armenian1k => "armenian_1k",
            Language::ArmenianWestern1k => "armenian_western_1k",
            Language::ArmenianWestern => "armenian_western",
            Language::Armenian => "armenian",
            Language::Azerbaijani1k => "azerbaijani_1k",
            Language::Azerbaijani => "azerbaijani",
            Language::Bangla10k => "bangla_10k",
            Language::BanglaLetters => "bangla_letters",
            Language::Bangla => "bangla",
            Language::Bashkir => "bashkir",
            Language::Belarusian100k => "belarusian_100k",
            Language::Belarusian10k => "belarusian_10k",
            Language::Belarusian1k => "belarusian_1k",
            Language::Belarusian25k => "belarusian_25k",
            Language::Belarusian50k => "belarusian_50k",
            Language::Belarusian5k => "belarusian_5k",
            Language::BelarusianLacinka1k => "belarusian_lacinka_1k",
            Language::BelarusianLacinka => "belarusian_lacinka",
            Language::Belarusian => "belarusian",
            Language::Bosnian4k => "bosnian_4k",
            Language::Bosnian => "bosnian",
            Language::BulgarianLatin => "bulgarian_latin",
            Language::Bulgarian => "bulgarian",
            Language::Catalan1k => "catalan_1k",
            Language::Catalan => "catalan",
            Language::ChineseSimplified10k => "chinese_simplified_10k",
            Language::ChineseSimplified1k => "chinese_simplified_1k",
            Language::ChineseSimplified50k => "chinese_simplified_50k",
            Language::ChineseSimplified5k => "chinese_simplified_5k",
            Language::ChineseSimplified => "chinese_simplified",
            Language::ChineseTraditional => "chinese_traditional",
            Language::CodeAbap1k => "code_abap_1k",
            Language::CodeAbap => "code_abap",
            Language::CodeArduino => "code_arduino",
            Language::CodeAssembly => "code_assembly",
            Language::CodeBash => "code_bash",
            Language::CodeBrainfck => "code_brainfck",
            Language::CodeC => "code_c",
            Language::CodeCpp => "code_c++",
            Language::CodeCobol => "code_cobol",
            Language::CodeCommonLisp => "code_common_lisp",
            Language::CodeCSharp => "code_csharp",
            Language::CodeCSS => "code_css",
            Language::CodeCuda => "code_cuda",
            Language::CodeDart => "code_dart",
            Language::CodeElixir => "code_elixir",
            Language::CodeFortran => "code_fortran",
            Language::CodeFSharp => "code_fsharp",
            Language::CodeGdscript2 => "code_gdscript_2",
            Language::CodeGdscript => "code_gdscript",
            Language::CodeGleam => "code_gleam",
            Language::CodeGo => "code_go",
            Language::CodeHaskell => "code_haskell",
            Language::CodeHtml => "code_html",
            Language::CodeJava => "code_java",
            Language::CodeJavascript1k => "code_javascript_1k",
            Language::CodeJavascriptReact => "code_javascript_react",
            Language::CodeJavascript => "code_javascript",
            Language::CodeJule => "code_jule",
            Language::CodeJulia => "code_julia",
            Language::CodeKotlin => "code_kotlin",
            Language::CodeLatex => "code_latex",
            Language::CodeLua => "code_lua",
            Language::CodeLuau => "code_luau",
            Language::CodeMatlab => "code_matlab",
            Language::CodeNim => "code_nim",
            Language::CodeNix => "code_nix",
            Language::CodeOdin => "code_odin",
            Language::CodeOok => "code_ook",
            Language::CodeOpenCL => "code_opencl",
            Language::CodePascal => "code_pascal",
            Language::CodePerl => "code_perl",
            Language::CodePhp => "code_php",
            Language::CodePowershell => "code_powershell",
            Language::CodePython1k => "code_python_1k",
            Language::CodePython2k => "code_python_2k",
            Language::CodePython5k => "code_python_5k",
            Language::CodePython => "code_python",
            Language::CodeR2k => "code_r_2k",
            Language::CodeR => "code_r",
            Language::CodeRockstar => "code_rockstar",
            Language::CodeRuby => "code_ruby",
            Language::CodeRust => "code_rust",
            Language::CodeScala => "code_scala",
            Language::CodeSQL => "code_sql",
            Language::CodeSwift => "code_swift",
            Language::CodeSystemVerilog => "code_systemverilog",
            Language::CodeTypescript => "code_typescript",
            Language::CodeTypst => "code_typst",
            Language::CodeV => "code_v",
            Language::CodeVim => "code_vim",
            Language::CodeVimscript => "code_vimscript",
            Language::CodeVisualBasic => "code_visual_basic",
            Language::CodeYoptascript => "code_yoptascript",
            Language::CodeZig => "code_zig",
            Language::Croatian1k => "croatian_1k",
            Language::Croatian => "croatian",
            Language::Czech10k => "czech_10k",
            Language::Czech1k => "czech_1k",
            Language::Czech => "czech",
            Language::Danish10k => "danish_10k",
            Language::Danish1k => "danish_1k",
            Language::Danish => "danish",
            Language::DockerFile => "docker_file",
            Language::Dutch10k => "dutch_10k",
            Language::Dutch1k => "dutch_1k",
            Language::Dutch => "dutch",
            Language::English10k => "english_10k",
            Language::English1k => "english_1k",
            Language::English25k => "english_25k",
            Language::English450k => "english_450k",
            Language::English5k => "english_5k",
            Language::EnglishCommonlyMisspelled => "english_commonly_misspelled",
            Language::EnglishContractions => "english_contractions",
            Language::EnglishDoubleletter => "english_doubleletter",
            Language::EnglishMedical => "english_medical",
            Language::EnglishOld => "english_old",
            Language::EnglishShakespearean => "english_shakespearean",
            Language::English => "english",
            Language::Esperanto10k => "esperanto_10k",
            Language::Esperanto1k => "esperanto_1k",
            Language::Esperanto25k => "esperanto_25k",
            Language::Esperanto36k => "esperanto_36k",
            Language::EsperantoHSistemo10k => "esperanto_h_sistemo_10k",
            Language::EsperantoHSistemo1k => "esperanto_h_sistemo_1k",
            Language::EsperantoHSistemo25k => "esperanto_h_sistemo_25k",
            Language::EsperantoHSistemo36k => "esperanto_h_sistemo_36k",
            Language::EsperantoHSistemo => "esperanto_h_sistemo",
            Language::EsperantoXSistemo10k => "esperanto_x_sistemo_10k",
            Language::EsperantoXSistemo1k => "esperanto_x_sistemo_1k",
            Language::EsperantoXSistemo25k => "esperanto_x_sistemo_25k",
            Language::EsperantoXSistemo36k => "esperanto_x_sistemo_36k",
            Language::EsperantoXSistemo => "esperanto_x_sistemo",
            Language::Esperanto => "esperanto",
            Language::Estonian10k => "estonian_10k",
            Language::Estonian1k => "estonian_1k",
            Language::Estonian5k => "estonian_5k",
            Language::Estonian => "estonian",
            Language::Euskera => "euskera",
            Language::Filipino1k => "filipino_1k",
            Language::Filipino => "filipino",
            Language::Finnish10k => "finnish_10k",
            Language::Finnish1k => "finnish_1k",
            Language::Finnish => "finnish",
            Language::French10k => "french_10k",
            Language::French1k => "french_1k",
            Language::French2k => "french_2k",
            Language::French600k => "french_600k",
            Language::FrenchBitoduc => "french_bitoduc",
            Language::French => "french",
            Language::Frisian1k => "frisian_1k",
            Language::Frisian => "frisian",
            Language::Friulian => "friulian",
            Language::Galician => "galician",
            Language::Georgian => "georgian",
            Language::German10k => "german_10k",
            Language::German1k => "german_1k",
            Language::German250k => "german_250k",
            Language::German => "german",
            Language::Git => "git",
            Language::Greek10k => "greek_10k",
            Language::Greek1k => "greek_1k",
            Language::Greek25k => "greek_25k",
            Language::Greek5k => "greek_5k",
            Language::Greek => "greek",
            Language::Greeklish10k => "greeklish_10k",
            Language::Greeklish1k => "greeklish_1k",
            Language::Greeklish25k => "greeklish_25k",
            Language::Greeklish5k => "greeklish_5k",
            Language::Greeklish => "greeklish",
            Language::Gujarati1k => "gujarati_1k",
            Language::Gujarati => "gujarati",
            Language::Hausa1k => "hausa_1k",
            Language::Hausa => "hausa",
            Language::Hawaiian1k => "hawaiian_1k",
            Language::Hawaiian => "hawaiian",
            Language::Hebrew10k => "hebrew_10k",
            Language::Hebrew1k => "hebrew_1k",
            Language::Hebrew5k => "hebrew_5k",
            Language::Hebrew => "hebrew",
            Language::Hindi1k => "hindi_1k",
            Language::Hindi => "hindi",
            Language::Hinglish => "hinglish",
            Language::Hungarian2k => "hungarian_2k",
            Language::Hungarian => "hungarian",
            Language::Icelandic1k => "icelandic_1k",
            Language::Icelandic => "icelandic",
            Language::Indonesian10k => "indonesian_10k",
            Language::Indonesian1k => "indonesian_1k",
            Language::Indonesian => "indonesian",
            Language::Irish => "irish",
            Language::Italian1k => "italian_1k",
            Language::Italian280k => "italian_280k",
            Language::Italian60k => "italian_60k",
            Language::Italian7k => "italian_7k",
            Language::Italian => "italian",
            Language::JapaneseHiragana => "japanese_hiragana",
            Language::JapaneseKatakana => "japanese_katakana",
            Language::JapaneseRomaji1k => "japanese_romaji_1k",
            Language::JapaneseRomaji => "japanese_romaji",
            Language::Jyutping => "jyutping",
            Language::Kabyle10k => "kabyle_10k",
            Language::Kabyle1k => "kabyle_1k",
            Language::Kabyle2k => "kabyle_2k",
            Language::Kabyle5k => "kabyle_5k",
            Language::Kabyle => "kabyle",
            Language::Kannada => "kannada",
            Language::Kazakh1k => "kazakh_1k",
            Language::Kazakh => "kazakh",
            Language::Khmer => "khmer",
            Language::Klingon1k => "klingon_1k",
            Language::Klingon => "klingon",
            Language::Korean1k => "korean_1k",
            Language::Korean5k => "korean_5k",
            Language::Korean => "korean",
            Language::KurdishCentral2k => "kurdish_central_2k",
            Language::KurdishCentral4k => "kurdish_central_4k",
            Language::KurdishCentral => "kurdish_central",
            Language::Kyrgyz1k => "kyrgyz_1k",
            Language::Kyrgyz => "kyrgyz",
            Language::Latin => "latin",
            Language::Latvian1k => "latvian_1k",
            Language::Latvian => "latvian",
            Language::LeagueOfLegends => "league_of_legends",
            Language::Lithuanian1k => "lithuanian_1k",
            Language::Lithuanian3k => "lithuanian_3k",
            Language::Lithuanian => "lithuanian",
            Language::LojbanCmavo => "lojban_cmavo",
            Language::LojbanGismu => "lojban_gismu",
            Language::LoremIpsum => "lorem_ipsum",
            Language::Macedonian10k => "macedonian_10k",
            Language::Macedonian1k => "macedonian_1k",
            Language::Macedonian75k => "macedonian_75k",
            Language::Macedonian => "macedonian",
            Language::Malagasy1k => "malagasy_1k",
            Language::Malagasy => "malagasy",
            Language::Malay1k => "malay_1k",
            Language::Malay => "malay",
            Language::Malayalam => "malayalam",
            Language::Maltese1k => "maltese_1k",
            Language::Maltese => "maltese",
            Language::Maori1k => "maori_1k",
            Language::Marathi => "marathi",
            Language::Mongolian10k => "mongolian_10k",
            Language::Mongolian => "mongolian",
            Language::MyanmarBurmese => "myanmar_burmese",
            Language::Nepali1k => "nepali_1k",
            Language::NepaliRomanized => "nepali_romanized",
            Language::Nepali => "nepali",
            Language::NorwegianBokmal10k => "norwegian_bokmal_10k",
            Language::NorwegianBokmal150k => "norwegian_bokmal_150k",
            Language::NorwegianBokmal1k => "norwegian_bokmal_1k",
            Language::NorwegianBokmal5k => "norwegian_bokmal_5k",
            Language::NorwegianBokmal600k => "norwegian_bokmal_600k",
            Language::NorwegianBokmal => "norwegian_bokmal",
            Language::NorwegianNynorsk100k => "norwegian_nynorsk_100k",
            Language::NorwegianNynorsk10k => "norwegian_nynorsk_10k",
            Language::NorwegianNynorsk1k => "norwegian_nynorsk_1k",
            Language::NorwegianNynorsk400k => "norwegian_nynorsk_400k",
            Language::NorwegianNynorsk5k => "norwegian_nynorsk_5k",
            Language::NorwegianNynorsk => "norwegian_nynorsk",
            Language::Occitan10k => "occitan_10k",
            Language::Occitan1k => "occitan_1k",
            Language::Occitan2k => "occitan_2k",
            Language::Occitan5k => "occitan_5k",
            Language::Occitan => "occitan",
            Language::Oromo1k => "oromo_1k",
            Language::Oromo5k => "oromo_5k",
            Language::Oromo => "oromo",
            Language::Pashto => "pashto",
            Language::Persian1k => "persian_1k",
            Language::Persian20k => "persian_20k",
            Language::Persian5k => "persian_5k",
            Language::PersianRomanized => "persian_romanized",
            Language::Persian => "persian",
            Language::PigLatin => "pig_latin",
            Language::Pinyin10k => "pinyin_10k",
            Language::Pinyin1k => "pinyin_1k",
            Language::Pinyin => "pinyin",
            Language::Polish10k => "polish_10k",
            Language::Polish200k => "polish_200k",
            Language::Polish20k => "polish_20k",
            Language::Polish2k => "polish_2k",
            Language::Polish40k => "polish_40k",
            Language::Polish5k => "polish_5k",
            Language::Polish => "polish",
            Language::Portuguese1k => "portuguese_1k",
            Language::Portuguese320k => "portuguese_320k",
            Language::Portuguese3k => "portuguese_3k",
            Language::Portuguese550k => "portuguese_550k",
            Language::Portuguese5k => "portuguese_5k",
            Language::PortugueseAcentosECedilha => "portuguese_acentos_e_cedilha",
            Language::Portuguese => "portuguese",
            Language::Quenya => "quenya",
            Language::Romanian100k => "romanian_100k",
            Language::Romanian10k => "romanian_10k",
            Language::Romanian1k => "romanian_1k",
            Language::Romanian200k => "romanian_200k",
            Language::Romanian25k => "romanian_25k",
            Language::Romanian50k => "romanian_50k",
            Language::Romanian5k => "romanian_5k",
            Language::Romanian => "romanian",
            Language::Russian10k => "russian_10k",
            Language::Russian1k => "russian_1k",
            Language::Russian25k => "russian_25k",
            Language::Russian375k => "russian_375k",
            Language::Russian50k => "russian_50k",
            Language::Russian5k => "russian_5k",
            Language::RussianAbbreviations => "russian_abbreviations",
            Language::RussianContractions1k => "russian_contractions_1k",
            Language::RussianContractions => "russian_contractions",
            Language::Russian => "russian",
            Language::SanskritRoman => "sanskrit_roman",
            Language::Sanskrit => "sanskrit",
            Language::Santali => "santali",
            Language::Serbian10k => "serbian_10k",
            Language::SerbianLatin10k => "serbian_latin_10k",
            Language::SerbianLatin => "serbian_latin",
            Language::Serbian => "serbian",
            Language::Shona1k => "shona_1k",
            Language::Shona => "shona",
            Language::Sinhala => "sinhala",
            Language::Slovak10k => "slovak_10k",
            Language::Slovak1k => "slovak_1k",
            Language::Slovak => "slovak",
            Language::Slovenian1k => "slovenian_1k",
            Language::Slovenian5k => "slovenian_5k",
            Language::Slovenian => "slovenian",
            Language::Spanish10k => "spanish_10k",
            Language::Spanish1k => "spanish_1k",
            Language::Spanish650k => "spanish_650k",
            Language::Spanish => "spanish",
            Language::Swahili1k => "swahili_1k",
            Language::Swedish1k => "swedish_1k",
            Language::SwedishDiacritics => "swedish_diacritics",
            Language::Swedish => "swedish",
            Language::SwissGerman1k => "swiss_german_1k",
            Language::SwissGerman2k => "swiss_german_2k",
            Language::SwissGerman => "swiss_german",
            Language::Tamil1k => "tamil_1k",
            Language::TamilOld => "tamil_old",
            Language::Tamil => "tamil",
            Language::Tanglish => "tanglish",
            Language::Tatar1k => "tatar_1k",
            Language::Tatar5k => "tatar_5k",
            Language::Tatar9k => "tatar_9k",
            Language::TatarCrimean10k => "tatar_crimean_10k",
            Language::TatarCrimean15k => "tatar_crimean_15k",
            Language::TatarCrimean1k => "tatar_crimean_1k",
            Language::TatarCrimean5k => "tatar_crimean_5k",
            Language::TatarCrimeanCyrillic10k => "tatar_crimean_cyrillic_10k",
            Language::TatarCrimeanCyrillic15k => "tatar_crimean_cyrillic_15k",
            Language::TatarCrimeanCyrillic1k => "tatar_crimean_cyrillic_1k",
            Language::TatarCrimeanCyrillic5k => "tatar_crimean_cyrillic_5k",
            Language::TatarCrimeanCyrillic => "tatar_crimean_cyrillic",
            Language::TatarCrimean => "tatar_crimean",
            Language::Tatar => "tatar",
            Language::Telugu1k => "telugu_1k",
            Language::Telugu => "telugu",
            Language::Thai10k => "thai_10k",
            Language::Thai1k => "thai_1k",
            Language::Thai20k => "thai_20k",
            Language::Thai50k => "thai_50k",
            Language::Thai5k => "thai_5k",
            Language::Thai60k => "thai_60k",
            Language::Thai => "thai",
            Language::Tibetan1k => "tibetan_1k",
            Language::Tibetan => "tibetan",
            Language::TokiPonaKuLili => "toki_pona_ku_lili",
            Language::TokiPonaKuSuli => "toki_pona_ku_suli",
            Language::TokiPona => "toki_pona",
            Language::Turkish1k => "turkish_1k",
            Language::Turkish5k => "turkish_5k",
            Language::Turkish => "turkish",
            Language::TwitchEmotes => "twitch_emotes",
            Language::TypingOfTheDead => "typing_of_the_dead",
            Language::Udmurt => "udmurt",
            Language::Ukrainian10k => "ukrainian_10k",
            Language::Ukrainian1k => "ukrainian_1k",
            Language::Ukrainian50k => "ukrainian_50k",
            Language::UkrainianEndings => "ukrainian_endings",
            Language::UkrainianLatynka10k => "ukrainian_latynka_10k",
            Language::UkrainianLatynka1k => "ukrainian_latynka_1k",
            Language::UkrainianLatynka50k => "ukrainian_latynka_50k",
            Language::UkrainianLatynkaEndings => "ukrainian_latynka_endings",
            Language::UkrainianLatynka => "ukrainian_latynka",
            Language::Ukrainian => "ukrainian",
            Language::Urdish => "urdish",
            Language::Urdu1k => "urdu_1k",
            Language::Urdu5k => "urdu_5k",
            Language::Urdu => "urdu",
            Language::Uzbek1k => "uzbek_1k",
            Language::Uzbek70k => "uzbek_70k",
            Language::Uzbek => "uzbek",
            Language::Vietnamese1k => "vietnamese_1k",
            Language::Vietnamese5k => "vietnamese_5k",
            Language::Vietnamese => "vietnamese",
            Language::ViossaNjutro => "viossa_njutro",
            Language::Viossa => "viossa",
            Language::Welsh1k => "welsh_1k",
            Language::Welsh => "welsh",
            Language::Wordle1k => "wordle_1k",
            Language::Wordle => "wordle",
            Language::Xhosa3k => "xhosa_3k",
            Language::Xhosa => "xhosa",
            Language::Yiddish => "yiddish",
            Language::Yoruba1k => "yoruba_1k",
            Language::Zulu => "zulu",
        };

        write!(f, "{string}")
    }
}

impl Default for Language {
    fn default() -> Self {
        Self::English
    }
}
